### ISSUE TITLE
Problem with new-style contrib

### ISSUE THREAD

**Issue by anttipoi** [paraseba/cssgen#5]
I cannot seem to get cssgen to work with clojure 1.3.0 and new style contribs.

cssgen depends on org.clojure/algo.generic. Referred version of that library has code under namespace clojure.algo.generic. Yet cssgen.use/css-ns refers to clojure.contrib.generic.arihmetic, which looks like old contrib stuff. 

What's the correct fix so old libs work, too?

**Comment by paraseba** [comment]
Sorry about that regression. Could you please try the new 0.2.6 version instead? It should fixed the problem.
Thanks for reporting the issue

**Comment by anttipoi** [comment]
Works like a charm, thanks!

**Comment by paraseba** [comment]
Great, thank you
