### ISSUE TITLE
Using jolby/colors

### ISSUE THREAD

**Issue by gf3** [paraseba/cssgen#6]
It might be worth using something like [jolby/colors](https://github.com/jolby/colors) for all the color props. That way we can use whatever representation we like, and just pass in a color.

For instance, I like to work with HSL because it's easier to grok, but ultimately I don't care what it ends up as in the stylesheet.

**Comment by paraseba** [comment]
Good idea, I'll take a deeper look soon. As always, patches welcomed.
Thanks for pointing this out.
